### ISSUE TITLE
Package control?

### ISSUE THREAD

**Issue by razzeee** [sublimelsp/LSP-elm#2]
Hey,

did not find this on package control, so I guess it's not ready yet?

Cheers

**Comment by predragnikolic** [comment]
It is not ready 🙂

**Comment by predragnikolic** [comment]
You can read more about the why it's not yet on package control here:
wbond/package_control_channel#7727 (comment)
sublimelsp/LSP#854 (comment)

**Comment by predragnikolic** [comment]
I have good news :)
https://packagecontrol.io/packages/LSP-elm

**Comment by razzeee** [comment]
Awesome, congrats on the release :) :tada: 

Are you going to post about this in reddic/slack/discourse?

**Comment by predragnikolic** [comment]
Thanks, elm looks like a really interesting type safe language :)
 > Are you going to post about this in reddis/slack/discourse?

I haven't made any public announcements so far for any plugin that we made. 
maybe there will be a day when I will write something about this... But I promise nothing :)

**Comment by razzeee** [comment]
Would you mind, if I do a post about this in the elm communities?

**Comment by predragnikolic** [comment]
I would be glad if you did that 🙂

**Comment by razzeee** [comment]
I've posted to https://discourse.elm-lang.org/t/lsp-elm-for-sublime-has-been-released/5522 and https://www.reddit.com/r/elm/comments/fzvx2b/lspelm_for_sublime_has_been_released/
I also posted it in the language server slack channel of the elm slack.

Have a nice weekend!

**Comment by predragnikolic** [comment]
Thanks! I just checked your README, and noticed that the first step can be removed :)

https://github.com/elm-tooling/elm-language-server#sublime

``` 
1. First install the language server via npm npm i -g @elm-tooling/elm-language-server
2. Install Elm Syntax Highlighting, LSP and LSP-elm from Package Control.
3. Restart Sublime.
```

The first step is not necessary, this plugin does that already :)

**Comment by razzeee** [comment]
Awesome, changed it, thanks for letting me know.
Does that mean, that you need to also push an update every-time I release a new server version?

**Comment by rchl** [comment]
Yes

**Comment by razzeee** [comment]
Do you think there is a way to make it as painless as possible for you?

I could create a PR every time changing these version numbers https://github.com/sublimelsp/LSP-elm/blob/master/server/package.json 
Is there anything more needed? You obviously need to publish to package-control too. Can that be automated, so that you just need to create the release/tag?

Sorry for all the questions.

**Comment by predragnikolic** [comment]
Dependabot is already set up for this repo. 
Each time you publish a new version of the elm-tooling/elm-language-server  to npm we will get a PR from dependabot.

For now I only need to manually checkout the PR and verify that the server starts. 
If everything is ok I merge the PR and make a release to Package Control.

I don't know if we could automate stuff like automatically merge the PR if the tests for starting the server pass(we don't have test like that currently)... And I don't know how I would setup GitHub to achive that. 

It is not that time consuming, but it would be great to automate as much as possible.
