### ISSUE TITLE
Setting not "elmAnalyseTrigger": "save" not respected

### ISSUE THREAD

**Issue by pdamoc** [sublimelsp/LSP-elm#37]
The elm-language-server is still triggered on change.

**Comment by predragnikolic** [comment]
Hello,

`elmAnalyseTrigger` was deprecated. 

The elm language server replaced elm-analyse with their own diagnostics, 
so they replaced the `elmAnalyseTrigger` with `onlyUpdateDiagnosticsOnSave`. 

I noticed that the elm language server changes the settings quiet often,
so I would suggest installing [LSP-json](https://packagecontrol.io/packages/LSP-json) as it would help you spot issues like this quicker. 

![image](https://user-images.githubusercontent.com/22029477/108085653-da3f5400-7075-11eb-8377-487c53c9d753.png)

I will close this issue, but if you have any problems, feel free to reopen it.
