### ISSUE TITLE
Add option to disable code reference

### ISSUE THREAD

**Issue by ivanbanov** [sublimelsp/LSP-elm#43]
As recommended in this thread https://forum.sublimetext.com/t/disable-references/58355 Im moving the discussion here

It would be nice to have an option to disable code reference (links in the right side), if you don't really use it (just like me) at some point it becomes pretty annoying 

![image](https://user-images.githubusercontent.com/2953018/120234544-7e7d8d00-c258-11eb-923b-7dc650fea313.png)

**Comment by rwols** [comment]
A quick skim through the server settings doesn't show me a way to disable just the reference code lenses (we call these things code lenses).

In any case, you can disable all code lenses by opening the LSP-elm preferences and adding:

```js
"disabled_capabilities": {
    "codeLensProvider": true
}
```

**Comment by ivanbanov** [comment]
hey @rwols, I tried it out but no success.

My `LSP-elm` config is

```json
{
  "disabled_capabilities": {
    "codeLensProvider": false
  },
  "settings": {
    "lsp_format_on_save": true
  }
}

```

Seems like the LSP is not reading it 🤔  none of the options work when set in the `LSP-elm` config

If I activate the `lsp_format_on_save` in the general config it does work, does it sound like a bug?

**Comment by rchl** [comment]
`lsp_format_on_save` is a global setting and doesn't work on plugin level.

As for disabling code lens, have you tried exactly how @rwols wrote (`true` instead of `false`)?

**Comment by ivanbanov** [comment]
Oh, it's my fault 🤦🏻‍♂️ I changed it to `false`, sorry for that

A bit sad the `lsp_format_on_save` can not be configured per `LSP`, Im probably misunderstanding the `settings` key so, would you mind pointing me to a doc explaining the `settings`?

I will close this issue, all good here 👌

**Comment by ivanbanov** [comment]
Oh, another doubt here, is there a global config for "disabled_capabilities"? I rarely use codelens, it would be nice to completely disable that in a global config :)

**Comment by rchl** [comment]
`settings` are specific to the server so differ per server.

`lsp_format_on_save` can be overridden per-project. See https://lsp.sublimetext.io/guides/client_configuration/#per-project-overrides

`disabled_capabilities` is currently not supported as a global setting.
