### ISSUE TITLE
Add required_node_version 14 - 16

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP-elm#51]
In the latest server version dropped node 12.

https://github.com/elm-tooling/elm-language-server/commit/11c307f48032fa1c3c88750b56fbc2ddad448321#diff-5abf59f5c477bf0988be5d44cf91cf60eb5a5766b820a489d38a3e46acc86344R18

Once, lsp_utils publishes a new version, use required_node_version to specify the node version.

**Comment by rchl** [comment]
Does it need the upper limit as the title suggests?

**Comment by predragnikolic** [comment]
I *assumed* that v16 is the upper limit because of the commit diff I attached, 
but now I see that v16 is just used for testing in github action...
so for now I would not constrain it to v16 and could use the minimum required node version method from lsp_utils.
